schedules:
  - cron: "0 0 * * 0" # https://crontab.guru/#0_0_*_*_0
    displayName: "Weekly Sunday build"
    branches:
      include:
        - master
    always: true

pool:
   vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    LTS:
      goVersion: '1.13'
    latest:
      goVersion: '1.14'
variables:
- name: LD_LIBRARY_PATH # used for guanzhi/GmSSL
  value: /usr/local/gmssl/lib

steps:
- script: cd $(Pipeline.Workspace); git clone https://github.com/guanzhi/GmSSL.git
  displayName: Clone GMSSL
- script: cd $(Pipeline.Workspace)/GmSSL; SYSTEM=`uname -s` ./config --prefix=/usr/local/gmssl; make; sudo make install_sw  
  displayName: Config, make and install GMSSL
- checkout: self
- task: GoTool@0
  inputs:
    version: $(goVersion)
- script: cd interop; go mod vendor
- script: cd pku-gm; go mod vendor
- script: cd interop; go test util_test.go pkuExport_test.go tjfocExport_test.go
  displayName: build artifacts
- script: cd interop; go test util_test.go pkuImport_test.go tjfocImport_test.go
  displayName: test on loading artifacts 