name: basicCI

on: 
  workflow_call:
    inputs:
      SOURCE: 
        required: true
        type: string
      TARGET: 
        required: true
        type: string
      ACTION:
        required: true
        type: string

env:
  LD_LIBRARY_PATH: /usr/local/gmssl/lib

jobs:
  sm2Interop_test:
    name: CI for interop
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
      with:
          go-version: 1.18
    - uses: actions/checkout@main
      with:
          repository: guanzhi/GmSSL
          path: GMSSL
          ref: master
    - run: SYSTEM=`uname -s` ./config --prefix=/usr/local/gmssl;
      working-directory: GMSSL
    - run: make
      working-directory: GMSSL
    - run: sudo make install_sw
      working-directory: GMSSL
      name: Config, make and install GMSSL
    - run: go mod vendor
      working-directory: interop
    - run: export ACTION=${{ inputs.ACTION }};export TARGET=${{ inputs.TARGET }};export SOURCE=${{ inputs.SOURCE }}; go test -v util_test.go sm2Interop_test.go tjSM2.go ccsSM2.go pkuSM2.go type.go
      working-directory: interop
      name: sm2 data interaction check