name: ccsPKUencrypt
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 3' # https://crontab.guru/#0_0_*_*_3
jobs:
  ccsPKUencrypt:
    uses: ./.github/workflows/basicCI.yml
    with:
      SOURCE: CCS
      TARGET: PKU
      ACTION: ENCRYPT
