name: java gm
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 3' # https://crontab.guru/#0_0_*_*_3
jobs:
  javaInterop_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
      with:
          go-version: 1.18
    - run: go mod vendor
      working-directory: interop
    - run: git clone https://github.com/Hyperledger-TWGC/java-gm.git
      name: Clone java-gm
    - run:  go test util_test.go tjfocExport_test.go
      working-directory: interop
      name: build artifacts - tjfoc
    - run: gradle build;
      working-directory: java-gm
      name: build artifacts - java
    - run: cp -f java-gm/*.pem ./interop/testdata/java/;
      name: copy java artifacts to testdata/java
    - run: go test -v util_test.go tjjavaImport_test.go
      working-directory: interop
      name: TJImportJava
    - run: cp -f ./interop/testdata/tjfoc/*.pem ./java-gm;
      name: copy tjfoc artifacts to java-gm
    - run: gradle build;
      working-directory: java-gm
      name: Java test on imported