name: PKUTJsign
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 3' # https://crontab.guru/#0_0_*_*_3
jobs:
  PKUTJsign:
    uses: ./.github/workflows/basicCI.yml
    with:
      SOURCE: PKU
      TARGET: TJ
      ACTION: SIGN