name: PKUtjsm4test
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 3' # https://crontab.guru/#0_0_*_*_3
jobs:
  PKUtjsm4test:
    uses: ./.github/workflows/basicCIsm4.yml
    with:
      SOURCE: PKU
      TARGET: TJ