name: sm3
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 3' # https://crontab.guru/#0_0_*_*_3
env:
  LD_LIBRARY_PATH: /usr/local/gmssl/lib
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
      with:
          go-version: 1.16
    - run: git clone https://github.com/guanzhi/GmSSL.git
      name: Clone GMSSL
    - run: cd GmSSL; SYSTEM=`uname -s` ./config --prefix=/usr/local/gmssl; make; sudo make install_sw  
      name: Config, make and install GMSSL
    - run: cd interop; go mod vendor
    - run: cd interop; go test -v util_test.go sm3Interop_test.go
      name: sm3 data interaction check