name: workshop code
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
        with:
          go-version: 1.16
    - run: cd workshop;go test -v ./... --cover