name: workshop code
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 3' # https://crontab.guru/#0_0_*_*_3
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
      with:
          go-version: 1.18
    - run: go test -v ./... --cover
      working-directory: workshop